# Generated by Django 4.2.2 on 2023-06-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_uniqueld_bookinstance_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('maint', 'Maintenance'), ('ol', 'On loan'), ('avi', 'Available'), ('rev', 'Reserved')], default='maint', help_text='Book availability', max_length=8),
        ),
    ]
